import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatOralInventory, getDayLabels } from '@/lib/utils'
import type { CycleCell, DrugInventoryDelta } from '@/types'

let cachedFont: string | null = null

async function loadCJKFont(doc: jsPDF): Promise<boolean> {
  try {
    if (!cachedFont) {
      const res = await fetch('/fonts/NotoSansTC.ttf')
      if (!res.ok) return false
      const buffer = await res.arrayBuffer()
      const bytes = new Uint8Array(buffer)
      let binary = ''
      for (let i = 0; i < bytes.length; i++) {
        binary += String.fromCharCode(bytes[i])
      }
      cachedFont = btoa(binary)
    }
    doc.addFileToVFS('NotoSansTC.ttf', cachedFont)
    doc.addFont('NotoSansTC.ttf', 'NotoSansTC', 'normal')
    return true
  } catch {
    return false
  }
}

export async function exportScheduleToPDF(
  title: string,
  totalWeeks: number,
  cells: CycleCell[],
  deltas?: DrugInventoryDelta[],
  startDate?: string | null
) {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  })

  const hasCJK = await loadCJKFont(doc)
  const fontName = hasCJK ? 'NotoSansTC' : 'helvetica'

  // Build cell map
  const cellMap = new Map<string, string[]>()
  for (const cell of cells) {
    if (cell.is_skipped) continue
    const key = `${cell.week_number}-${cell.day_of_week}`
    if (!cellMap.has(key)) cellMap.set(key, [])
    if (cell.display_value) cellMap.get(key)!.push(cell.display_value)
  }

  doc.setFont(fontName)
  doc.setFontSize(16)
  doc.text(title, 14, 15)

  // Schedule table
  const headers = ['Week', ...getDayLabels(startDate)]
  const body: string[][] = []

  for (let week = 1; week <= totalWeeks; week++) {
    const row = [`Week ${week}`]
    for (let day = 1; day <= 7; day++) {
      const entries = cellMap.get(`${week}-${day}`) || []
      row.push(entries.join('\n'))
    }
    body.push(row)
  }

  autoTable(doc, {
    startY: 22,
    head: [headers],
    body,
    theme: 'grid',
    headStyles: {
      fillColor: [40, 40, 40],
      textColor: [255, 255, 255],
      fontSize: 9,
      halign: 'center',
      fontStyle: 'bold',
      font: fontName,
    },
    bodyStyles: {
      fontSize: 7,
      cellPadding: 2,
      valign: 'top',
      lineWidth: 0.1,
      font: fontName,
    },
    columnStyles: {
      0: { cellWidth: 20, halign: 'center', valign: 'middle', fontStyle: 'bold' },
      1: { cellWidth: 35 },
      2: { cellWidth: 35 },
      3: { cellWidth: 35 },
      4: { cellWidth: 35 },
      5: { cellWidth: 35 },
      6: { cellWidth: 35 },
      7: { cellWidth: 35 },
    },
    styles: {
      overflow: 'linebreak',
      cellWidth: 'wrap',
      font: fontName,
    },
    margin: { left: 10, right: 10 },
    didDrawPage: () => {
      doc.setFont(fontName)
      doc.setFontSize(7)
      doc.setTextColor(150)
      doc.text(
        `Generated by Cycle Planner - ${new Date().toLocaleDateString('zh-TW')}`,
        14,
        doc.internal.pageSize.height - 8
      )
    },
  })

  // Drug stats table — on a new page
  if (deltas && deltas.length > 0) {
    doc.addPage()

    doc.setFont(fontName)
    doc.setFontSize(11)
    doc.setTextColor(0)
    doc.text(hasCJK ? '藥物用量統計' : 'Drug Stats', 14, 15)

    const statsHeaders = hasCJK ? ['藥物', '需求量'] : ['Drug', 'Needed']
    const statsBody = deltas.map((d) => {
      const isOral = d.category === 'Oral' || d.category === 'PCT'
      const isE3D = d.ester_type === 'E3D'
      const needed = isOral
        ? `${Math.round(d.needed_ml)} ${hasCJK ? '顆' : 'tabs'} (${formatOralInventory(Math.round(d.needed_ml), d.tabs_per_box)})`
        : isE3D
          ? `${d.needed_vials} ${hasCJK ? '瓶/劑' : 'vials'}`
          : `${d.needed_ml} ml (${d.needed_vials} ${hasCJK ? '瓶' : 'vials'})`
      return [d.drug_name, needed]
    })

    autoTable(doc, {
      startY: 20,
      head: [statsHeaders],
      body: statsBody,
      theme: 'grid',
      headStyles: {
        fillColor: [40, 40, 40],
        textColor: [255, 255, 255],
        fontSize: 8,
        halign: 'center',
        fontStyle: 'bold',
        font: fontName,
      },
      bodyStyles: {
        fontSize: 8,
        cellPadding: 2,
        font: fontName,
      },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 60, halign: 'right' },
      },
      styles: {
        font: fontName,
      },
      margin: { left: 10, right: 10 },
      tableWidth: 100,
    })
  }

  doc.save(`${title.replace(/[/\\?%*:|"<>]/g, '_')}.pdf`)
}
